// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktvtbohgrqybkfvnzsvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dnRib2hncnF5Ymtmdm56c3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODIxNjEsImV4cCI6MjA3MTk1ODE2MX0.VV902tPU2eIbxGIxx93WHHvXpwnLR8CCbw93lcQAbsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});